### ISSUE TITLE
Adding GPX files

### ISSUE THREAD

**Issue by clinton2111** [sharklatan/SharkGo#1]
Hello there,
I have created a GPX file using https://mapstogpx.com and placed it in my `sharkgo/gpx/route` folder but for some reason, the GPX files don't seem to be loaded. Also Trying to access the GUI from http://192.168.0.179:49217 doesnt seem to work anymore, just a white screen

![image](https://github.com/sharklatan/SharkGo/assets/3950377/903aa341-2568-4547-895c-2c2b7c836f4e)

Attached GPX file for testing
Thank you for your assistance 

https://gist.github.com/clinton2111/863e12c9ffed68390c3c31aaafa5aef6

**Comment by sharklatan** [comment]
Hello,

First and foremost, I want to inform you that until version 1.8, the local access part was handled differently. However, due to best practices, we decided to separate the page from the project. This was because the changes or corrections were minor but more frequent, and releasing a complete update for each of them made it difficult to distinguish if the user had a corrected version. Additionally, this would cause the user to download the executable more times than necessary due to direct implementations in the frontend.

Regarding the version 1.8 you mentioned, it’s important to note that it did not introduce specialized route management in its code. Nevertheless, it’s relevant to mention that there were some beta versions provided to some users. It’s possible that the version you’re referring to is a preliminary version prior to version 2.0. However, it’s important to highlight that these preliminary versions had errors that have been corrected in versions 2.0.0.2 and later.

Some of the errors included route limitations, which required clicking the route button again after completing a route. There were also issues with excessive memory consumption during the route process, leading to instability and closing of the executable.

Regarding your current inquiry:

You can use the routes of your choice. The file should be placed in the installation directory at ‘Gpx/route/file.gpx.’ For example, you can rename it as ‘pier.gpx’ and place your personal file with that name. The program will automatically detect it.

Furthermore, I wanted to inform you that we are working on a new implementation that will be available in the upcoming version 2.0.0.3. With this update, files should be placed in the ‘Gpx/custom/’ directory with the ‘*.gpx’ extension. This directory will automatically list all GPX files contained within it, and these will be considered your personal routes. You will only need to assign them a name for identification.


Remember, this is an open-source project in which you can contribute, whether through code, ideas, or suggestions. You can have a significant impact. Feel free to submit pull requests or suggest improvements; they will be tested and reviewed as needed. Remember, together, we can make this project even better.


If you have any further questions or encounter any issues, please don’t hesitate to seek assistance.

Best regards,
Shark
